######################################################################
#
# File name : comb_SA_tb_wave.do
# Created on: Tue Mar 31 18:19:08 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
