onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /comb_SA_tb/clk
add wave -noupdate /comb_SA_tb/rst_b
add wave -noupdate /comb_SA_tb/mode
add wave -noupdate /comb_SA_tb/start
add wave -noupdate /comb_SA_tb/data
add wave -noupdate /comb_SA_tb/addr
add wave -noupdate /comb_SA_tb/finish
add wave -noupdate /comb_SA_tb/full_rank
add wave -noupdate /comb_SA_tb/result
add wave -noupdate /comb_SA_tb/q
add wave -noupdate /comb_SA_tb/f
add wave -noupdate /comb_SA_tb/i
add wave -noupdate /comb_SA_tb/start_time
add wave -noupdate /comb_SA_tb/DUT/DAT_W
add wave -noupdate /comb_SA_tb/DUT/clk
add wave -noupdate /comb_SA_tb/DUT/rst_b
add wave -noupdate /comb_SA_tb/DUT/mode
add wave -noupdate /comb_SA_tb/DUT/start
add wave -noupdate /comb_SA_tb/DUT/data
add wave -noupdate /comb_SA_tb/DUT/finish
add wave -noupdate /comb_SA_tb/DUT/full_rank
add wave -noupdate -color Yellow /comb_SA_tb/DUT/result
add wave -noupdate /comb_SA_tb/DUT/start_tmp
add wave -noupdate /comb_SA_tb/DUT/start_row
add wave -noupdate /comb_SA_tb/DUT/data_col0
add wave -noupdate /comb_SA_tb/DUT/data_col1
add wave -noupdate /comb_SA_tb/DUT/data_col2
add wave -noupdate /comb_SA_tb/DUT/data_col3
add wave -noupdate /comb_SA_tb/DUT/data_in
add wave -noupdate /comb_SA_tb/DUT/start_in_0_0
add wave -noupdate /comb_SA_tb/DUT/start_out_0_0
add wave -noupdate /comb_SA_tb/DUT/op_in_0_0
add wave -noupdate /comb_SA_tb/DUT/op_out_0_0
add wave -noupdate /comb_SA_tb/DUT/r_0_0
add wave -noupdate /comb_SA_tb/DUT/data_in_0_0
add wave -noupdate /comb_SA_tb/DUT/data_out_0_0
add wave -noupdate /comb_SA_tb/DUT/pivot_in_0_0
add wave -noupdate /comb_SA_tb/DUT/pivot_out_0_0
add wave -noupdate /comb_SA_tb/DUT/start_in_0_1
add wave -noupdate /comb_SA_tb/DUT/start_out_0_1
add wave -noupdate /comb_SA_tb/DUT/op_in_0_1
add wave -noupdate /comb_SA_tb/DUT/op_out_0_1
add wave -noupdate /comb_SA_tb/DUT/r_0_1
add wave -noupdate /comb_SA_tb/DUT/data_in_0_1
add wave -noupdate /comb_SA_tb/DUT/data_out_0_1
add wave -noupdate /comb_SA_tb/DUT/pivot_in_0_1
add wave -noupdate /comb_SA_tb/DUT/pivot_out_0_1
add wave -noupdate /comb_SA_tb/DUT/start_in_0_2
add wave -noupdate /comb_SA_tb/DUT/start_out_0_2
add wave -noupdate /comb_SA_tb/DUT/op_in_0_2
add wave -noupdate /comb_SA_tb/DUT/op_out_0_2
add wave -noupdate /comb_SA_tb/DUT/r_0_2
add wave -noupdate /comb_SA_tb/DUT/data_in_0_2
add wave -noupdate /comb_SA_tb/DUT/data_out_0_2
add wave -noupdate /comb_SA_tb/DUT/pivot_in_0_2
add wave -noupdate /comb_SA_tb/DUT/pivot_out_0_2
add wave -noupdate /comb_SA_tb/DUT/start_in_0_3
add wave -noupdate /comb_SA_tb/DUT/start_out_0_3
add wave -noupdate /comb_SA_tb/DUT/op_in_0_3
add wave -noupdate /comb_SA_tb/DUT/op_out_0_3
add wave -noupdate /comb_SA_tb/DUT/r_0_3
add wave -noupdate /comb_SA_tb/DUT/data_in_0_3
add wave -noupdate /comb_SA_tb/DUT/data_out_0_3
add wave -noupdate /comb_SA_tb/DUT/pivot_in_0_3
add wave -noupdate /comb_SA_tb/DUT/pivot_out_0_3
add wave -noupdate /comb_SA_tb/DUT/start_in_1_0
add wave -noupdate /comb_SA_tb/DUT/start_out_1_0
add wave -noupdate /comb_SA_tb/DUT/op_in_1_0
add wave -noupdate /comb_SA_tb/DUT/op_out_1_0
add wave -noupdate /comb_SA_tb/DUT/r_1_0
add wave -noupdate /comb_SA_tb/DUT/data_in_1_0
add wave -noupdate /comb_SA_tb/DUT/data_out_1_0
add wave -noupdate /comb_SA_tb/DUT/pivot_in_1_0
add wave -noupdate /comb_SA_tb/DUT/pivout_out_1_0
add wave -noupdate /comb_SA_tb/DUT/pivot_out_1_0
add wave -noupdate /comb_SA_tb/DUT/start_in_1_1
add wave -noupdate /comb_SA_tb/DUT/start_out_1_1
add wave -noupdate /comb_SA_tb/DUT/op_in_1_1
add wave -noupdate /comb_SA_tb/DUT/op_out_1_1
add wave -noupdate /comb_SA_tb/DUT/r_1_1
add wave -noupdate /comb_SA_tb/DUT/data_in_1_1
add wave -noupdate /comb_SA_tb/DUT/data_out_1_1
add wave -noupdate /comb_SA_tb/DUT/pivot_in_1_1
add wave -noupdate /comb_SA_tb/DUT/pivot_out_1_1
add wave -noupdate /comb_SA_tb/DUT/start_in_1_2
add wave -noupdate /comb_SA_tb/DUT/start_out_1_2
add wave -noupdate /comb_SA_tb/DUT/op_in_1_2
add wave -noupdate /comb_SA_tb/DUT/op_out_1_2
add wave -noupdate /comb_SA_tb/DUT/r_1_2
add wave -noupdate /comb_SA_tb/DUT/data_in_1_2
add wave -noupdate /comb_SA_tb/DUT/data_out_1_2
add wave -noupdate /comb_SA_tb/DUT/pivot_in_1_2
add wave -noupdate /comb_SA_tb/DUT/pivot_out_1_2
add wave -noupdate /comb_SA_tb/DUT/start_in_1_3
add wave -noupdate /comb_SA_tb/DUT/start_out_1_3
add wave -noupdate /comb_SA_tb/DUT/op_in_1_3
add wave -noupdate /comb_SA_tb/DUT/op_out_1_3
add wave -noupdate /comb_SA_tb/DUT/r_1_3
add wave -noupdate /comb_SA_tb/DUT/data_in_1_3
add wave -noupdate /comb_SA_tb/DUT/data_out_1_3
add wave -noupdate /comb_SA_tb/DUT/pivot_in_1_3
add wave -noupdate /comb_SA_tb/DUT/pivot_out_1_3
add wave -noupdate /comb_SA_tb/DUT/start_in_2_0
add wave -noupdate /comb_SA_tb/DUT/start_out_2_0
add wave -noupdate /comb_SA_tb/DUT/op_in_2_0
add wave -noupdate /comb_SA_tb/DUT/op_out_2_0
add wave -noupdate /comb_SA_tb/DUT/r_2_0
add wave -noupdate /comb_SA_tb/DUT/data_in_2_0
add wave -noupdate /comb_SA_tb/DUT/data_out_2_0
add wave -noupdate /comb_SA_tb/DUT/pivot_in_2_0
add wave -noupdate /comb_SA_tb/DUT/pivout_out_2_0
add wave -noupdate /comb_SA_tb/DUT/pivot_out_2_0
add wave -noupdate /comb_SA_tb/DUT/start_in_2_1
add wave -noupdate /comb_SA_tb/DUT/start_out_2_1
add wave -noupdate /comb_SA_tb/DUT/op_in_2_1
add wave -noupdate /comb_SA_tb/DUT/op_out_2_1
add wave -noupdate /comb_SA_tb/DUT/r_2_1
add wave -noupdate /comb_SA_tb/DUT/data_in_2_1
add wave -noupdate /comb_SA_tb/DUT/data_out_2_1
add wave -noupdate /comb_SA_tb/DUT/pivot_in_2_1
add wave -noupdate /comb_SA_tb/DUT/pivot_out_2_1
add wave -noupdate /comb_SA_tb/DUT/start_in_2_2
add wave -noupdate /comb_SA_tb/DUT/start_out_2_2
add wave -noupdate /comb_SA_tb/DUT/op_in_2_2
add wave -noupdate /comb_SA_tb/DUT/op_out_2_2
add wave -noupdate /comb_SA_tb/DUT/r_2_2
add wave -noupdate /comb_SA_tb/DUT/data_in_2_2
add wave -noupdate /comb_SA_tb/DUT/data_out_2_2
add wave -noupdate /comb_SA_tb/DUT/pivot_in_2_2
add wave -noupdate /comb_SA_tb/DUT/pivot_out_2_2
add wave -noupdate /comb_SA_tb/DUT/start_in_2_3
add wave -noupdate /comb_SA_tb/DUT/start_out_2_3
add wave -noupdate /comb_SA_tb/DUT/op_in_2_3
add wave -noupdate /comb_SA_tb/DUT/op_out_2_3
add wave -noupdate /comb_SA_tb/DUT/r_2_3
add wave -noupdate /comb_SA_tb/DUT/data_in_2_3
add wave -noupdate /comb_SA_tb/DUT/data_out_2_3
add wave -noupdate /comb_SA_tb/DUT/pivot_in_2_3
add wave -noupdate /comb_SA_tb/DUT/pivot_out_2_3
add wave -noupdate /comb_SA_tb/DUT/start_in_3_0
add wave -noupdate /comb_SA_tb/DUT/start_out_3_0
add wave -noupdate /comb_SA_tb/DUT/op_in_3_0
add wave -noupdate /comb_SA_tb/DUT/op_out_3_0
add wave -noupdate /comb_SA_tb/DUT/r_3_0
add wave -noupdate /comb_SA_tb/DUT/data_in_3_0
add wave -noupdate /comb_SA_tb/DUT/data_out_3_0
add wave -noupdate /comb_SA_tb/DUT/pivot_in_3_0
add wave -noupdate /comb_SA_tb/DUT/pivout_out_3_0
add wave -noupdate /comb_SA_tb/DUT/pivot_out_3_0
add wave -noupdate /comb_SA_tb/DUT/start_in_3_1
add wave -noupdate /comb_SA_tb/DUT/start_out_3_1
add wave -noupdate /comb_SA_tb/DUT/op_in_3_1
add wave -noupdate /comb_SA_tb/DUT/op_out_3_1
add wave -noupdate /comb_SA_tb/DUT/r_3_1
add wave -noupdate /comb_SA_tb/DUT/data_in_3_1
add wave -noupdate /comb_SA_tb/DUT/data_out_3_1
add wave -noupdate /comb_SA_tb/DUT/pivot_in_3_1
add wave -noupdate /comb_SA_tb/DUT/pivot_out_3_1
add wave -noupdate /comb_SA_tb/DUT/start_in_3_2
add wave -noupdate /comb_SA_tb/DUT/start_out_3_2
add wave -noupdate /comb_SA_tb/DUT/op_in_3_2
add wave -noupdate /comb_SA_tb/DUT/op_out_3_2
add wave -noupdate /comb_SA_tb/DUT/r_3_2
add wave -noupdate /comb_SA_tb/DUT/data_in_3_2
add wave -noupdate /comb_SA_tb/DUT/data_out_3_2
add wave -noupdate /comb_SA_tb/DUT/pivot_in_3_2
add wave -noupdate /comb_SA_tb/DUT/pivot_out_3_2
add wave -noupdate /comb_SA_tb/DUT/start_in_3_3
add wave -noupdate /comb_SA_tb/DUT/start_out_3_3
add wave -noupdate /comb_SA_tb/DUT/op_in_3_3
add wave -noupdate /comb_SA_tb/DUT/op_out_3_3
add wave -noupdate /comb_SA_tb/DUT/r_3_3
add wave -noupdate /comb_SA_tb/DUT/data_in_3_3
add wave -noupdate /comb_SA_tb/DUT/data_out_3_3
add wave -noupdate /comb_SA_tb/DUT/pivot_in_3_3
add wave -noupdate /comb_SA_tb/DUT/pivot_out_3_3
add wave -noupdate /comb_SA_tb/DUT/pivot_found
add wave -noupdate -itemcolor Red /comb_SA_tb/DUT/row0
add wave -noupdate -itemcolor Red /comb_SA_tb/DUT/row1
add wave -noupdate -itemcolor Red /comb_SA_tb/DUT/row2
add wave -noupdate -itemcolor Red /comb_SA_tb/DUT/row3
add wave -noupdate /comb_SA_tb/DUT/result_col0
add wave -noupdate /comb_SA_tb/DUT/result_col1
add wave -noupdate /comb_SA_tb/DUT/result_col2
add wave -noupdate /comb_SA_tb/DUT/result_col3
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/clk
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/mode
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/r
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_0/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/clk
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/mode
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/r
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_1/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/clk
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/mode
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/r
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_2/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/clk
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/mode
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/r
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_0_3/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/clk
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/mode
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/r
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_0/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/clk
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/mode
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/r
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_1/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/clk
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/mode
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/r
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_2/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/clk
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/mode
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/r
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_1_3/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/clk
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/mode
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/r
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_0/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/clk
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/mode
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/r
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_1/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/clk
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/mode
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/r
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_2/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/clk
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/mode
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/r
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_2_3/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/clk
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/mode
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/r
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_0/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/clk
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/mode
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/r
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_1/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/clk
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/mode
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/r
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_2/pivot_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/clk
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/rst_b
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/mode
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/start_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/data_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/op_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/pivot_in
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/start_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/data_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/op_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/pivot_out
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/r
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/r_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/data_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/op_out_reg
add wave -noupdate /comb_SA_tb/DUT/AB_3_3/pivot_out_reg
add wave -noupdate /comb_SA_tb/MEM/WIDTH
add wave -noupdate /comb_SA_tb/MEM/DEPTH
add wave -noupdate /comb_SA_tb/MEM/FILE
add wave -noupdate /comb_SA_tb/MEM/INIT
add wave -noupdate /comb_SA_tb/MEM/clock
add wave -noupdate /comb_SA_tb/MEM/data
add wave -noupdate /comb_SA_tb/MEM/rdaddress
add wave -noupdate /comb_SA_tb/MEM/rden
add wave -noupdate /comb_SA_tb/MEM/wraddress
add wave -noupdate /comb_SA_tb/MEM/wren
add wave -noupdate /comb_SA_tb/MEM/q
add wave -noupdate /comb_SA_tb/MEM/file
add wave -noupdate /comb_SA_tb/MEM/scan
add wave -noupdate /comb_SA_tb/MEM/i
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {264248 ps} 0} {{Cursor 2} {294923 ps} 0} {{Cursor 3} {974736 ps} 0}
quietly wave cursor active 3
configure wave -namecolwidth 348
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {925925 ps} {1028221 ps}
