######################################################################
#
# File name : comb_SA_tb_wave.do
# Created on: Fri Mar 20 11:12:58 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
