######################################################################
#
# File name : comb_SA_tb_compile.do
# Created on: Fri Nov 20 11:15:19 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\modelsim_10.5\\win64\\vlib modelsim_lib/work
D:\\modelsim_10.5\\win64\\vlib modelsim_lib/msim

D:\\modelsim_10.5\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_10.5\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\modelsim_10.5\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../Verilog" \
"../../../../Verilog/comb_SA.v" \
"../../../../Verilog/mem.v" \
"../../../../Verilog/node.v" \
"../../../../Verilog/comb_SA_tb.v" \


# compile glbl module
D:\\modelsim_10.5\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

